openapi: "3.0.3"

info:
  title: "Code Connect API"
  description: |
    Code Connectで利用するAPIの定義
    # Feature
    - theme
      - テーマをサーバーから取得するAPI
    - code
      - ユーザーが作成したコードをサーバーに送信する機能

    More Info =>  Notion
  version: "0.1.0"

servers:
  - url: http://localhost:{port}
    description: Local development
    variables:
      port:
        enum: ["3000", "8080"]
        default: "8080"

tags:
  - name: Theme
    description: テーマを管理するAPI
  - name: Code
    description: コードを操作するAPI

components:
  schemas:
    theme:
      type: object
      properties:
        id:
          type: number
          example: 1
        theme:
          type: string
          example: "Hello Worldを出力する"
    post_body:
      type: object
      properties:
        themeId:
          type: number
          example: 1
        language:
          type: string
          example: ts
        code:
          type: string
          example: 'console.log("Hello World")'
    code_response:
      type: object
      properties:
        id:
          type: number
        themeId:
          type: number
        code:
          type: string
        timeStamp:
          type: string
    score:
      type: object
      properties:
        your_type:
          type: string
          example: Your Type
        type_description:
          type: string
          example: Type description
        code_line:
          type: number
          example: 10
        token_len:
          type: number
          example: 20
        token_count:
          type: number
          example: 30
        function_len:
          type: number
          example: 10

paths:
  "/api/theme":
    get:
      summary: "APIサーバーからテーマデータの一覧を受け取るためのAPI"
      tags:
        - "Theme"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/theme"
  "/api/code":
    post:
      summary: "ユーザーが作成したコードをサーバーに送信するためのAPI"
      tags:
        - "Code"
      requestBody:
        description: "ユーザーが作成したコードをサーバーに送信する"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_body"
      responses:
        "200":
          description: "サーバーで評価された結果を取得するためのデータ"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/code_response"
  "/api/result":
    get:
      summary: IDから評価結果を取得する
      tags:
        - "Code"
      parameters:
        - name: id
          in: query
          schema:
            type: number
      responses:
        "200":
          description: サーバーで評価されたデータ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/score"
