openapi: "3.0.3"

info:
  title: "API"
  version: "0.1.0"

components:
  schemas:
    room:
      type: object
      properties:
        id:
          type: string
          example: "0000"
    status_ok:
      type: object
      properties:
        status:
          type: string
          example: ok
        name:
          type: string
          example: Delete
    status_failure:
      type: object
      properties:
        status:
          type: string
          example: failure
        reason:
          type: string
          example: Attempted to delete a non-existent room.
        name:
          type: string
          example: Delete

    theme:
      type: object
      properties:
        id:
          type: number
          example: 1
        theme:
          type: string
          example: "Hello Worldを出力する"
    post_body:
      type: object
      properties:
        id:
          type: number
          example: 1
        code:
          type: string
          example: 'console.log("Hello World")'
    score:
      type: object
      properties:
        code_line:
          type: number
          example: 10
        token_len:
          type: number
          example: 20
        token_count:
          type: number
          example: 30
        function_len:
          type: number
          example: 10

paths:
  "/api/room/create":
    get:
      tags:
        - "room"
      summary: "ルームに関するAPI"
      responses:
        "200":
          description: "作成されたルームのID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
  "/api/room/delete":
    get:
      tags:
        - "room"
      summary: "ルームを削除するAPI"
      parameters:
        - name: id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/room"

      responses:
        "200":
          description: "ルームを削除する"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status_ok"
        "400":
          description: "不正なリクエスト"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status_failure"

  "/api/theme":
    get:
      summary: "APIサーバーからデータを受け取るためのAPI"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/theme"
  "/api/code":
    post:
      summary: "ユーザーが作成したコードをサーバーに送信するためのAPI"
      requestBody:
        description: "ユーザーが作成したコードをサーバーに送信する"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  $ref: "#/components/schemas/post_body"
      responses:
        "200":
          description: "サーバーで評価したスコア"
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    $ref: "#/components/schemas/score"
